# Generated by Django 4.2 on 2024-07-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="country"
            ),
        ),
    ]
