# Generated by Django 5.0.6 on 2024-06-25 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_blog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["title", "slug"],
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
            },
        ),
    ]
