# Generated by Django 5.0.6 on 2024-07-03 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_blog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.FloatField(verbose_name="version_number")),
                (
                    "version_name",
                    models.CharField(max_length=100, verbose_name="version_name"),
                ),
                (
                    "version_is_active",
                    models.BooleanField(default=False, verbose_name="is_active"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version",
                        to="catalog.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия",
                "verbose_name_plural": "Версии",
            },
        ),
        migrations.DeleteModel(
            name="Blog",
        ),
    ]
